name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - "platform/terraform/**"
      - ".github/workflows/terraform-ci.yml"

  pull_request:
    branches:
      - main
    paths:
      - "platform/terraform/**"
      - ".github/workflows/terraform-ci.yml"

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: platform/terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.8"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive ../../

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate
